version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12081984zZ
      MYSQL_DATABASE: test_aws
      MYSQL_USER: root
      MYSQL_PASSWORD: 12081984zZ
